name: Automerge changes
description: Automatically merges changes
author: Quizlet
inputs:
  token:
    description: Personal access token (PAT) used to perform actions against the repository
    default: ${{ github.token }}
  target:
    description: Branch to merge the changes into. If not set, the target will be the default branch for the repo
    required: false
  patterns:
    description: List of patterns to check for changes. Can be comma or newline separated. If not set, all changes will be comitted
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
