name: Commit changes
description: Automatically commits changes
author: Quizlet
inputs:
  token:
    description: Personal access token (PAT) used to perform actions against the repository
    default: ${{ github.token }}
  branch:
    description: Branch to merge the changes into. If not set, the target will be the default branch for the repo
    required: false
  message:
    description: Message for the resulting commit
    required: true
  append-run-info:
    description: Appends information about the run to the commit message
    default: true
  files:
    description: List of patterns to commit. Multiple patterns can be split with newlines
    required: true
outputs:
  sha:
    description: SHA of the commit. Will be an empty string if there was nothing to commit.
runs:
  using: 'node12'
  main: 'dist/index.js'
