name: Automerge changes
description: Automatically merges changes
author: Quizlet
inputs:
  token:
    description: Personal access token (PAT) used to perform actions against the repository
    default: ${{ github.token }}
  target:
    description: Branch to merge the changes into
    default: master
  patterns:
    description: List of patterns to check for changes. Can be comma or newline separated. If not provided, all changes will be comitted
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
