name: Auto Merge

on:
  pull_request_target:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Auto-merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2.6
        with:
          github-token: ${{ secrets.QUIZLET_GIT_BOT_TOKEN }}
          command: squash and merge
          config: .github/auto-merge.yaml
