name: Check and Test
on: # rebuild any PRs and main branch changes
  pull_request:
    types: ['opened', 'synchronize']
  push:
    branches:
      - main
      - 'releases/*'

env:
  HUSKY_SKIP_INSTALL: '1'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install deps
        run: npm ci
      - name: Check formatting
        run: npm run format-check
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Package
        run: npm run package
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          milliseconds: 1000
