name: Check, Build, and Run
on:
  pull_request:
    types: ['opened', 'synchronize']
  push:
    branches:
      - main
      - 'releases/*'

env:
  HUSKY_SKIP_INSTALL: '1'

jobs:
  check:
    name: Run code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.0.1
      - name: Setup node
        uses: actions/setup-node@v2.5.1
        with:
          node-version-file: .node-version
          cache: npm
      - name: Install deps
        run: npm ci
      - name: Check formatting
        run: npm run format-check
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
  build:
    name: Build action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.0.1
      - name: Setup node
        uses: actions/setup-node@v2.5.1
        with:
          node-version-file: .node-version
          cache: npm
      - name: Install deps
        run: npm ci
      - name: Build action
        run: npm run build
      - name: Verify no unstaged changes
        run: .github/util/verify-no-unstaged-changes.sh
# TODO(cooper): Disabling these integration tests until we fix dependabot PR
#   run-action:
#     name: Run action
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3.0.1
#       - name: Generate files to commit
#         run: |
#           echo "$(date): Testing ${GITHUB_SHA}" > test.txt
#           echo "static value" > static.txt
#       - name: Run action against test with default token
#         uses: ./
#         with:
#           branch: test
#           message: ':robot: Test commit'
#           glob-patterns: test.txt
#       - name: Run action against protected-test with admin token
#         uses: ./
#         with:
#           token: ${{ secrets.QUIZLET_GIT_BOT_TOKEN }}
#           branch: protected-test
#           message: ':robot: Test commit'
#           glob-patterns: test.txt
#       - name: Run action against unchanged file
#         id: unchanged-commit
#         uses: ./
#         with:
#           branch: test
#           message: ':robot: Test commit of static.txt'
#           glob-patterns: static.txt
#       - name: Fail if unchanged file was committed
#         run: |
#           if [[ -n "${{steps.unchanged-commit.outputs.sha}}" ]]
#           then
#             echo "::error::Action commited the unchanged file"
#             exit 1
#           fi
