name: Check and Run
on:
  pull_request:
    types: ['opened', 'synchronize']
  push:
    branches:
      - main
      - 'releases/*'

env:
  HUSKY_SKIP_INSTALL: '1'

jobs:
  check:
    name: Run code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install deps
        run: npm ci
      - name: Check formatting
        run: npm run format-check
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Package
        run: npm run package
  run-action:
    name: Run action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Generate file to commit
        run: 'echo "$(date): Testing ${GITHUB_SHA}" > test.txt'
      - uses: ./
        with:
          branch: test
          mesage: ':robot: Test commit'
          patterns: test.txt
